In [10]:
import pandas as pd

### Charger les données

In [11]:
df = pd.read_csv('../processed/clean_global.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176 entries, 0 to 1175
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   timestamp          1176 non-null   object
 1   building_id        1176 non-null   object
 2   sensor_id          1176 non-null   object
 3   temperature        1176 non-null   float64
 4   humidity           1176 non-null   float64
 5   power_consumption  1176 non-null   float64
dtypes: float64(3), object(3)
memory usage: 55.3+ KB

### Indicateur global

In [20]:
df.describe()

       temperature     humidity  power_consumption
count  1176.000000  1176.000000        1176.000000
mean     20.985204    58.040731         687.969388
std       3.661487     6.655336          96.846476
min      14.000000    41.500000         380.000000
25%      17.500000    52.900000         619.000000
50%      21.000000    58.000000         686.000000
75%      24.500000    63.400000         758.250000
max      28.400000    74.800000         963.000000

### Conversion en datetime puis ajout d'une colonne 'date'

In [17]:
df['date'] = pd.to_datetime(df['timestamp']).dt.date

### Calcul des indicateurs pour le power_consumption

In [15]:

power_consumption = (
    df.groupby(['building_id', 'date'])
      .agg(
        moyenne=('power_consumption', 'mean'),
        minimum=('power_consumption', 'min'),
        maximum=('power_consumption', 'max'),
        ecart_type=('power_consumption', 'std')
      )
      .reset_index()
)
power_consumption

   building_id        date     moyenne  minimum  maximum  ecart_type
0         B001  2025-10-01  644.347826    446.0    793.0  100.769588
1         B001  2025-10-02  626.333333    453.0    821.0   99.915036
2         B001  2025-10-03  640.695652    505.0    803.0   88.557857
3         B001  2025-10-04  642.250000    462.0    874.0   99.903976
4         B001  2025-10-05  634.818182    481.0    823.0   95.042164
5         B002  2025-10-01  666.291667    518.0    840.0   85.292071
6         B002  2025-10-02  653.750000    464.0    778.0   93.216555
7         B002  2025-10-03  625.956522    440.0    786.0  105.077235
8         B002  2025-10-04  655.708333    467.0    836.0   91.900456
9         B002  2025-10-05  641.958333    506.0    786.0   79.665321
10        B003  2025-10-01  664.625000    532.0    791.0   77.622169
11        B003  2025-10-02  672.217391    480.0    759.0   76.875316
12        B003  2025-10-03  667.291667    442.0    788.0   87.940928
13        B003  2025-10-04  638.750000    380.0    777.0  110.281162
14        B003  2025-10-05  677.500000    544.0    781.0   65.524639
15        B004  2025-10-01  658.217391    494.0    784.0   70.476919
16        B004  2025-10-02  671.347826    472.0    860.0   97.325886
17        B004  2025-10-03  672.409091    504.0    865.0   89.543104
18        B004  2025-10-04  667.291667    505.0    822.0   83.998695
19        B004  2025-10-05  673.478261    430.0    877.0  121.279493
20        B005  2025-10-01  655.125000    518.0    780.0   70.300790
21        B005  2025-10-02  684.708333    509.0    933.0  104.084614
22        B005  2025-10-03  684.166667    455.0    845.0  102.996693
23        B005  2025-10-04  670.291667    491.0    852.0  100.435781
24        B005  2025-10-05  666.500000    574.0    766.0   58.465151
25        B006  2025-10-01  684.863636    544.0    847.0   87.630879
26        B006  2025-10-02  702.041667    498.0    886.0  101.396972
27        B006  2025-10-03  699.083333    586.0    823.0   75.589806
28        B006  2025-10-04  679.478261    565.0    819.0   72.146234
29        B006  2025-10-05  673.458333    527.0    861.0   89.556385
30        B007  2025-10-01  719.954545    558.0    865.0   87.523318
31        B007  2025-10-02  706.272727    478.0    836.0   91.403439
32        B007  2025-10-03  696.260870    484.0    866.0   92.186184
33        B007  2025-10-04  728.695652    560.0    922.0   92.926870
34        B007  2025-10-05  688.875000    508.0    823.0   90.395418
35        B008  2025-10-01  709.666667    562.0    887.0  100.475248
36        B008  2025-10-02  720.208333    509.0    879.0  100.236234
37        B008  2025-10-03  721.458333    526.0    952.0  104.233008
38        B008  2025-10-04  717.826087    541.0    893.0  103.479753
39        B008  2025-10-05  705.708333    589.0    877.0   83.942775
40        B009  2025-10-01  722.125000    539.0    869.0   89.745201
41        B009  2025-10-02  742.583333    588.0    926.0   91.496694
42        B009  2025-10-03  747.826087    538.0    963.0  116.926804
43        B009  2025-10-04  736.750000    584.0    883.0   81.441497
44        B009  2025-10-05  740.541667    576.0    898.0   95.945174
45        B010  2025-10-01  753.500000    611.0    856.0   78.722407
46        B010  2025-10-02  737.913043    564.0    858.0   87.317557
47        B010  2025-10-03  737.521739    582.0    862.0   80.999927
48        B010  2025-10-04  740.750000    540.0    951.0  103.637852
49        B010  2025-10-05  727.291667    546.0    951.0  102.252237

### Calcul des indicateurs pour l'humidité

In [16]:
humidity = (
    df.groupby(['building_id', 'date'])
      .agg(
        moyenne=('humidity', 'mean'),
        minimum=('humidity', 'min'),
        maximum=('humidity', 'max'),
        ecart_type=('humidity', 'std')
      )
      .reset_index()
)
humidity

   building_id        date    moyenne  minimum  maximum  ecart_type
0         B001  2025-10-01  57.847826     44.2     68.1    6.389257
1         B001  2025-10-02  57.120833     48.7     67.0    5.233502
2         B001  2025-10-03  58.630435     44.8     68.0    6.829710
3         B001  2025-10-04  58.800000     46.6     71.7    7.307947
4         B001  2025-10-05  58.372727     47.1     68.5    6.130345
5         B002  2025-10-01  58.454167     47.2     70.1    6.466703
6         B002  2025-10-02  57.333333     45.8     68.3    7.207464
7         B002  2025-10-03  56.604348     42.6     65.6    5.352355
8         B002  2025-10-04  57.408333     44.4     68.0    7.000057
9         B002  2025-10-05  57.520833     43.9     70.2    6.301137
10        B003  2025-10-01  58.041667     47.1     69.4    6.253828
11        B003  2025-10-02  58.126087     44.4     70.4    6.572340
12        B003  2025-10-03  58.250000     47.3     71.3    7.361238
13        B003  2025-10-04  57.008333     43.3     69.3    6.845177
14        B003  2025-10-05  59.012500     44.7     69.8    7.531055
15        B004  2025-10-01  58.321739     44.9     71.2    6.912963
16        B004  2025-10-02  57.482609     43.0     70.5    7.241337
17        B004  2025-10-03  58.381818     50.2     67.9    5.785996
18        B004  2025-10-04  58.962500     48.0     70.4    7.148537
19        B004  2025-10-05  57.543478     44.4     71.3    7.220100
20        B005  2025-10-01  58.616667     45.4     70.4    6.554830
21        B005  2025-10-02  57.241667     48.8     66.0    5.330300
22        B005  2025-10-03  58.075000     44.1     70.8    7.825668
23        B005  2025-10-04  57.920833     42.8     69.4    7.473663
24        B005  2025-10-05  57.966667     43.3     73.6    7.746509
25        B006  2025-10-01  58.045455     50.0     68.4    5.836072
26        B006  2025-10-02  58.525000     48.7     71.6    6.585640
27        B006  2025-10-03  58.012500     44.7     70.0    6.525489
28        B006  2025-10-04  57.665217     48.5     68.1    6.350777
29        B006  2025-10-05  58.550000     46.1     72.0    7.483315
30        B007  2025-10-01  58.268182     47.6     74.8    6.696437
31        B007  2025-10-02  58.213636     47.8     71.9    6.530755
32        B007  2025-10-03  56.752174     44.5     67.0    6.238944
33        B007  2025-10-04  58.108696     46.9     69.5    7.386530
34        B007  2025-10-05  57.387500     46.8     69.3    7.188173
35        B008  2025-10-01  58.270833     49.5     71.1    5.747928
36        B008  2025-10-02  57.845833     43.6     69.9    7.521793
37        B008  2025-10-03  58.337500     47.0     69.1    6.478312
38        B008  2025-10-04  59.378261     45.7     74.4    7.018026
39        B008  2025-10-05  58.116667     45.4     69.2    7.246448
40        B009  2025-10-01  57.912500     46.5     68.8    6.518156
41        B009  2025-10-02  57.529167     46.2     69.4    6.806869
42        B009  2025-10-03  58.769565     48.0     73.7    7.170865
43        B009  2025-10-04  57.987500     45.5     69.8    6.486261
44        B009  2025-10-05  57.045833     41.5     68.6    7.616914
45        B010  2025-10-01  58.225000     48.5     71.2    6.750604
46        B010  2025-10-02  56.739130     43.3     67.6    7.016846
47        B010  2025-10-03  59.482609     49.2     72.9    6.761095
48        B010  2025-10-04  59.408333     48.1     68.5    5.801868
49        B010  2025-10-05  58.458333     44.4     69.0    6.727356

### Calcul des indicateurs pour la température

In [21]:
temperature = (
    df.groupby(['building_id', 'date'])
      .agg(
        moyenne=('temperature', 'mean'),
        minimum=('temperature', 'min'),
        maximum=('temperature', 'max'),
        ecart_type=('temperature', 'std')
      )
      .reset_index()
)
temperature

   building_id        date    moyenne  minimum  maximum  ecart_type
0         B001  2025-10-01  20.382609     14.4     25.9    3.728594
1         B001  2025-10-02  20.287500     14.1     26.0    3.705966
2         B001  2025-10-03  20.386957     14.0     26.9    4.031276
3         B001  2025-10-04  20.404167     14.7     25.8    3.645543
4         B001  2025-10-05  20.454545     14.7     26.6    4.152191
5         B002  2025-10-01  20.600000     14.9     26.5    3.741425
6         B002  2025-10-02  20.595833     14.8     26.3    3.732173
7         B002  2025-10-03  20.469565     14.2     26.8    3.630732
8         B002  2025-10-04  20.295833     14.0     27.4    4.015890
9         B002  2025-10-05  20.545833     15.9     26.1    3.579893
10        B003  2025-10-01  20.804167     15.4     27.0    3.452092
11        B003  2025-10-02  20.617391     14.8     26.0    3.740522
12        B003  2025-10-03  20.412500     14.8     24.8    3.605227
13        B003  2025-10-04  20.641667     15.6     27.1    3.711195
14        B003  2025-10-05  20.841667     15.5     27.1    3.702633
15        B004  2025-10-01  20.300000     14.7     26.1    3.839744
16        B004  2025-10-02  21.104348     15.3     26.5    3.455230
17        B004  2025-10-03  20.863636     16.1     27.9    3.746433
18        B004  2025-10-04  20.841667     15.3     26.4    3.679191
19        B004  2025-10-05  20.739130     15.4     27.3    3.836634
20        B005  2025-10-01  20.812500     15.0     25.6    3.487906
21        B005  2025-10-02  20.683333     14.8     25.9    3.665547
22        B005  2025-10-03  20.958333     15.2     27.4    3.926600
23        B005  2025-10-04  20.562500     14.8     26.0    3.788749
24        B005  2025-10-05  20.866667     15.6     26.2    3.570491
25        B006  2025-10-01  20.427273     15.6     25.8    3.620600
26        B006  2025-10-02  21.100000     15.0     26.7    3.324481
27        B006  2025-10-03  20.816667     15.1     26.5    3.469327
28        B006  2025-10-04  21.013043     15.8     26.8    3.757696
29        B006  2025-10-05  20.729167     14.4     26.5    3.793069
30        B007  2025-10-01  21.340909     16.3     27.3    3.783883
31        B007  2025-10-02  21.363636     16.5     26.6    3.574186
32        B007  2025-10-03  21.143478     14.0     26.7    3.909874
33        B007  2025-10-04  21.708696     15.0     27.9    3.741525
34        B007  2025-10-05  21.175000     16.1     26.6    3.491013
35        B008  2025-10-01  21.337500     14.9     26.3    3.565269
36        B008  2025-10-02  21.637500     16.0     27.3    3.760760
37        B008  2025-10-03  21.320833     16.1     26.9    3.635212
38        B008  2025-10-04  21.373913     15.0     26.5    3.727931
39        B008  2025-10-05  21.391667     15.0     27.3    3.635683
40        B009  2025-10-01  21.770833     14.9     28.1    3.905568
41        B009  2025-10-02  21.404167     16.0     28.4    3.921898
42        B009  2025-10-03  21.534783     16.3     27.0    3.678266
43        B009  2025-10-04  21.616667     16.1     27.4    3.701312
44        B009  2025-10-05  21.600000     15.4     27.4    3.848433
45        B010  2025-10-01  21.716667     16.0     27.5    3.742897
46        B010  2025-10-02  21.730435     16.4     27.6    3.489000
47        B010  2025-10-03  21.700000     16.9     26.5    3.531160
48        B010  2025-10-04  21.420833     15.8     26.7    3.805257
49        B010  2025-10-05  21.391667     15.2     27.1    3.800334